name: CD compute permission

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:

jobs:
  cd-event:
    if: github.ref_name == 'prod' || github.ref_name == 'preprod'

    runs-on: ubuntu-latest

    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set AWS Credentials
        uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: |
            {
              "github_token": "${{ secrets.GITHUB_TOKEN }}",
              "POJA_AWS_ACCESS_KEY_ID": "${{ secrets.POJA_AWS_ACCESS_KEY_ID }}",
              "POJA_AWS_SECRET_ACCESS_KEY": "${{ secrets.POJA_AWS_SECRET_ACCESS_KEY }}",
              "POJA_GH_USERNAME": "${{ secrets.POJA_GH_USERNAME }}",
              "POJA_GH_TOKEN": "${{ secrets.POJA_GH_TOKEN }}"
            }
          region: eu-west-3
        env:
          AWS_REGION: eu-west-3


      - name: Deploy permission stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.ref_name }}-permission-harena-com
          template: cf-stacks/compute-permission-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"harena-com\" }, { \"Key\": \"env\", \"Value\": \"${{ github.ref_name }}\" }, { \"Key\": \"user:poja\", \"Value\": \"harena-com\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ github.ref_name }}"
